## consumer https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html
## producer https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html
---
version: '3'
services:
  kafka-connect:
    image: confluentinc/cp-kafka-connect-base
    build:
      context: ./
    container_name: kafka-connect
    ports:
      - 8083:8083
    environment:
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_REST_PORT: 8083
      CONNECT_REST_LISTENERS: "http://kafka-connect:8083"
      CONNECT_LISTENERS: "http://kafka-connect:8083"
      CONNECT_HOST_NAME: "kafka-connect"
      



      CONNECT_BOOTSTRAP_SERVERS: "${KAFKA_HOST}:${KAFKA_PORT}"
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      # Cannot be higher than the number of brokers in the Kafka cluster
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      #KAFKA_REST_PROXY_URL: "http://127.0.0.0.1:8083"
